# 线上配置文件
server:
  address: 0.0.0.0
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 over time
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: mybi-backend
#    swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # session config
  session:
    # todo Uncomment enables distributed session（Redis first）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    # MySQL 5.7
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mybi
    username: root
    password: root
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
#    password: 123456
  rabbitmq:
    port: 5672
    password: guest
    username: guest
    host: rabbitmq
  # file upload
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 生产环境关闭日志
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # logic delete
      logic-delete-value: 1
      logic-not-delete-value: 0
#AI
yuapi:
  client:
    access-key: inq1qlktc892ikvq7kl67vodc6qvurdi
    secret-key: 5chw0wvisoc33w87x76ethehymunu238