spring:
  application:
    name: mybi-backend
  # default dev env
  profiles:
    active: dev
  #  swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session config
  session:
    # todo Uncomment enables distributed session（Redis first）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # database config
  # todo config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybi
    username: root
    password: root
  # Redis
  # todo config
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000
#   password: 123456
# RabbitMQ
  rabbitmq:
    port: 5672
    password: guest
    username: guest
    host: localhost
  # Elasticsearch config
  # todo config
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # file upload
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 over time
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # logic delete
      logic-delete-value: 1
      logic-not-delete-value: 0


# about wx
wx:
  # wx public Account
  # todo config
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # wx open plant
  # todo config
  open:
    appId: xxx
    appSecret: xxx
# object save
# todo config
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

#AI
yuapi:
  client:
    access-key: inq1qlktc892ikvq7kl67vodc6qvurdi
    secret-key: 5chw0wvisoc33w87x76ethehymunu238
